USE project;

CREATE TABLE Users (
 ID INT( 11 ) NOT NULL AUTO_INCREMENT ,
 Username VARCHAR( 30 ) NOT NULL ,
 Email VARCHAR( 50 ) NOT NULL ,
 Password VARCHAR( 128 ) NOT NULL ,
 PRIMARY KEY ( ID ) ,
 UNIQUE KEY Username (Username)
) DEFAULT CHARSET = utf8;